export const auth = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_SIGNUP: "USER_SIGNUP",
  CLEAR_ERROR_MESSAGE : "CLEAR_ERROR_MESSAGE",
};
export const members = {
  GET_LIST_MEMBERS: "GET_LIST_MEMBERS",
  GET_MEMBER_DETAILS_FROM_TEMP_LIST :  "GET_MEMBER_DETAILS_FROM_TEMP_LIST",
  CREATE_NEW_MEMBER : "CREATE_NEW_MEMBER",
  GET_MEMBER_DETAILS : "GET_MEMBER_DETAILS",
  EDIT_MEMBER_DETAILS : "EDIT_MEMBER_DETAILS",
  DELETE_MEMBER : "DELETE_MEMBER",
  SEARCH_MEMBER : "SEARCH_MEMBER",
  FILTER_MEMBER : "FILTER_MEMBER",
  CLEAR_FILTER_LIST: "CLEAR_FILTER_LIST",
  GET_MEMBER_NOT_MANAGE_TEAM : "GET_MEMBER_NOT_MANAGE_TEAM",
  CLEAR_MEMBER_ERROR_MESSAGE : "CLEAR_MEMBER_ERROR_MESSAGE",

};
export const position = {
  GET_POSITION_LIST: "GET_POSITION_LIST",
  GET_POSITION_DETAILS : "GET_POSITION_DETAILS",
  CREATE_NEW_POSITION : "CREATED_NEW_POSITION",
  EDIT_POSITION_DETAILS : "EDIT_POSITION_DETAILS",
  DELETE_POSITION : "DELETE_POSITION",
  FILTER_POSITION : "FILTER_POSITION",
  CLEAR_FILTERED_POSITION_LIST: "CLEAR_FILTERED_POSITION_LIST",
  CLEAR_POSITION_ERROR_MESSAGE : "CLEAR_POSITION_ERROR_MESSAGE",


};
export const team = {
  GET_TEAM_LIST: "GET_TEAM_LIST",
  GET_TEAM_DETAILS : "GET_TEAM_DETAILS",
  CREATE_NEW_TEAM: "CREATED_NEW_TEAM",
  EDIT_TEAM_DETAILS : "EDIT_TEAM_DETAILS",
  DELETE_TEAM : "DELETE_TEAM",
  FILTER_TEAM : "FILTER_TEAM",
  CLEAR_FILTERED_TEAM_LIST: "CLEAR_FILTERED_TEAM_LIST",
  CLEAR_TEAM_ERROR_MESSAGE : "CLEAR_TEAM_ERROR_MESSAGE",
  GET_TEAM_BY_LEADER_ID : "GET_TEAM_BY_LEADER_ID"
};

export const user = {
  GET_USER_LIST: "GET_USER_LIST",
  GET_USER_DETAILS : "GET_USER_DETAILS",
  CREATE_NEW_USER: "CREATED_NEW_USER",
  EDIT_USER_DETAILS : "EDIT_USER_DETAILS",
  DELETE_USER : "DELETE_USER",
  FILTER_USER : "FILTER_USER",
  CLEAR_FILTERED_USER_LIST: "CLEAR_FILTERED_USER_LIST",
  ACTIVE_USER : "ACTIVE_USER",
  UNACTIVE_USER : "UNACTIVE_USER",
  CLEAR_USER_ERROR_MESSAGE : "CLEAR_USER_ERROR_MESSAGE",

};
