export const auth = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_SIGNUP: "USER_SIGNUP",
};
export const members = {
  GET_LIST_MEMBERS: "GET_LIST_MEMBERS",
  SET_MEMBER_DETAILS_FROM_TEMP_LIST :  "SET_MEMBER_DETAILS_FROM_TEMP_LIST",
  CREATE_NEW_MEMBER : "CREATE_NEW_MEMBER",
  GET_MEMBER_DETAILS : "GET_MEMBER_DETAILS",
  EDIT_MEMBER_DETAILS : "EDIT_MEMBER_DETAILS",
  DELETE_MEMBER : "DELETE_MEMBER",
  SEARCH_MEMBER : "SEARCH_MEMBER",
  FILTER_MEMBER : "FILTER_MEMBER",
  CLEAR_FILTER_LIST: "CLEAR_FILTER_LIST",
};
export const position = {
  GET_POSITION_LIST: "GET_POSITION_LIST",
  GET_POSITION_DETAILS : "GET_POSITION_DETAILS",
  CREATE_NEW_POSITION : "CREATED_NEW_POSITION",
  EDIT_POSITION_DETAILS : "EDIT_POSITION_DETAILS",
  DELETE_POSITION : "DELETE_POSITION"

};
export const team = {
  GET_TEAM_LIST: "GET_TEAM_LIST",
  GET_TEAM_DETAILS : "GET_TEAM_DETAILS",
  CREATE_NEW_TEAM: "CREATED_NEW_TEAM",
  EDIT_TEAM_DETAILS : "EDIT_TEAM_DETAILS",
  DELETE_TEAM : "DELETE_TEAM"
};
